/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for uuid
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <libraries/uuid.h>

#include <interfaces/uuid.h>
#include <proto/exec.h>
#include <assert.h>

/****************************************************************************/

struct Library * uuidBase = NULL;
static struct Library * __uuidBase;

/****************************************************************************/

void uuid_base_constructor(void)
{
    if (uuidBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __uuidBase = uuidBase = (struct Library *)IExec->OpenLibrary("uuid.library", 0L);
    assert(uuidBase != NULL);
}
__attribute__((section(".ctors.zzzz"))) static void
(*uuid_base_constructor_ptr)(void) USED = uuid_base_constructor;

/****************************************************************************/

void uuid_base_destructor(void)
{
    if (__uuidBase)
    {
        IExec->CloseLibrary((struct Library *)__uuidBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*uuid_base_destructor_ptr)(void) USED = uuid_base_destructor;

/****************************************************************************/

