#ifndef UUID_INTERFACE_DEF_H
#define UUID_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_UUID_H
#include <libraries/uuid.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct UuidIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct UuidIFace *Self);
	ULONG APICALL (*Release)(struct UuidIFace *Self);
	void APICALL (*Expunge)(struct UuidIFace *Self);
	struct Interface * APICALL (*Clone)(struct UuidIFace *Self);
	void * APICALL (*UuidA)(struct UuidIFace *Self, const struct TagItem * taglist);
	void * APICALL (*Uuid)(struct UuidIFace *Self, ...);
	void APICALL (*FreeUuid)(struct UuidIFace *Self, void * uuid);
	void APICALL (*UuidToText)(struct UuidIFace *Self, void * uuid, char * text);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* UUID_INTERFACE_DEF_H */
