
/* This file was generated by idltool 53.6. Do not edit */

#include "uuid_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    _uuid_Obtain,
    _uuid_Release,
    NULL,
    NULL,
    _uuid_UuidA,
    _uuid_Uuid,
    _uuid_FreeUuid,
    _uuid_UuidToText,
    (APTR)-1
};

