on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: build
    steps:
    - name: ppc build
      id: build
      uses: actions/checkout@v1
      uses: chris-y/amigaos-cross-docker-action@12bf175f83c39103328f3697420509591dcc2f1a
      with:
        makefile: 'uuid_files/Makefile'
