#ifndef INLINE4_UUID_H
#define INLINE4_UUID_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_UUID_H
#include <libraries/uuid.h>
#endif
#include <interfaces/uuid.h>

/* Inline macros for Interface "main" */
#define UuidA(taglist) IUuid->UuidA((taglist)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define Uuid(...) IUuid->Uuid(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define Uuid(...) IUuid->Uuid(## vargs) 
#endif
#define FreeUuid(uuid) IUuid->FreeUuid((uuid)) 
#define UuidToText(uuid, text) IUuid->UuidToText((uuid), (text)) 

#endif /* INLINE4_UUID_H */
